graduation_assessment/config/routes.rb
Rails.application.routes.draw do

  resources :messages
  get "api/messages" => "api#index"
  root "messages#new"

end

graduation_assessment/app/models/message.rb
class Message < ActiveRecord::Base
end

graduation_assessment/app/controllers/api_controller.rb
class ApiController < ApplicationController

	def index
		render json: {messages: Message.all}
	end
end

graduation_assessment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

graduation_assessment/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@messages = Message.all
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)

		if @message.save
			flash[:notice] = "Thanks for adding a message!"
			redirect_to messages_path
		else
			flash[:notice] = "Something went wrong when adding your new message..."
			render :new
		end
	end

	private
	def message_params
		params.require(:message).permit(:name, :body)
	end
end

graduation_assessment/app/helpers/api_helper.rb
module ApiHelper
end

graduation_assessment/app/helpers/application_helper.rb
module ApplicationHelper
end

graduation_assessment/app/helpers/messages_helper.rb
module MessagesHelper
end

graduation_assessment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraduationAssessment</title>

</head>
<body>

<%= yield %>

</body>
</html>

graduation_assessment/app/views/messages/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>


<% @messages.each do |message| %>

	<div>
		<h3><%= message.name %> signed the guestbook <%= time_ago_in_words(message.created_at) %> ago:</h3>
		<%= message.body %><br><br>
	</div>

<% end %>

<%= link_to "Sign Again!", new_message_path %>

graduation_assessment/app/views/messages/new.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
 
<h1>Welcome! Please sign the guest book</h1>

<%= form_for @message do |form| %>

	<div>
		<%= form.label :name %><br>
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :message %><br>
		<%= form.text_area :body %><br>
	</div>

	<div>
		<%= form.submit %>
	</div>

<% end %>